### ISSUE TITLE
README.md

### ISSUE THREAD

**Issue by volodymyr-kushnir** [BrykAlex/bsa#1]
@BrykAlex since you're trying to learn how to use **git**, may I suggest creating a [**Project**](https://github.com/BrykAlex/bsa/projects) first? Also see [**this for more hints and lifehacks**](https://github.com/volodymyr-kushnir/agenda), also let me know @volodymyr-kushnir if you have any questions. Oh, and yes, **README.md** with a short description of your project would be very nice to have as well.

**Comment by BrykAlex** [comment]
@volodymyr-kushnir thanks for advice. I hope I haven't caused you trouble at the weekend.

**Comment by volodymyr-kushnir** [comment]
@BrykAlex why, no, of course not. You have your tasks, I have mine (: as simple as that, no trouble at all. Give me a shout @volodymyr-kushnir if you need some question answered or anything.

**Comment by BrykAlex** [comment]
@volodymyr-kushnir If I understand correctly, in master branch should be two articles without comments. Comments are added in new branches. So we must have branch for each comment. It's right?

**Comment by volodymyr-kushnir** [comment]
@BrykAlex поломаю тобі дзен в Issues і перейду на українську. В общєм, спочатку _README.md_, потім _стаття раз_ одною гілкою, мердж, _стаття два_ іншою гілкою, мердж. _Коменти до обох статей_ ще іншою гілкою, мердж. Отак нормально. Насправді якоїсь чіткої схеми нема, в кожного своя логіка і можна кожен комент окремою гілкою впроваджувати, чого б нє.

**Comment by BrykAlex** [comment]
@volodymyr-kushnir дуже дякую. Тепер зрозумів.

**Comment by volodymyr-kushnir** [comment]
@BrykAlex закрив тобі issue вручну. А взагалі, можна закривати issues автоматично, якщо коммітити з повідомленням типу **"Blah-blah-blah (fixes #1)"** — **GitHub** зрозуміє _fixes_ і  закриє issue номер такий-то.
